print("      ··········BERENGUIFY!!··········")
print("-Et donam la benvinguda a la primera edició de Berenguify!! ")
print("              ._.Menú._.         ")
print("1. Afegir una cançó: ")
print("2. Registra un usuari: ")
print("3. Veure cançons disponibles: ")
print("4. Veure usuaris del sistema: ")
print("5. Sortir del programa: ")
input("Tria una de les opcions previament mostrades: ")
print()
print("        ___Canço-1___")
nom=input("Nom de la canço: ")
Autor=input("Autor de la canço: ")
any_de_llençament=input("Any de llençament: ")
estil=input("L'estil de música: ")
print()
input("Pitja una tecla per afegir un altre canço: ")
print(Fore.BLUE+"     ___Canço-2___")
nom1=input("Nom de la canço: ")
Autor1=input("Autor de la canço: ")
any_de_llençament1=input("Any de llençament: ")
estil1=input("L'estil de música: ")
print()
input("Pitja una tecla per afegir un usuari: ")
print(Fore.MAGENTA+"     ___Usuari-1___")
nom_complet=input("Nom i llnatges: ")
data_de_naixement=input("Data de neixament: ") 
correu_electrònic=input("Correu electrònic: ")
població=input("Població on visquis: ")
print()
input("Pitja una tecla per afegir un altre usuari: ")
print(Fore.YELLOW+"     ___Usuari-2___")
nom_complet1=input("Nom i llnatges: ")
data_de_naixement1=input("Data de neixament: ") 
correu_electrònic1=input("Correu electrònic: ")
població1=input("Població on visquis: ")
print()
input("Pitja una tecla per veure les cançons disponibles: ")
print("        ___Canço-1___")
print("Nom de la canço: " + nom)
print("Autor de la canço: " + Autor)
print("Any de llençament: " + any_de_llençament)
print("L'estil de música: " + estil)
print()
print("        ___Canço-2___")
print("Nom de la canço: " + nom1)
print("Autor de la canço: " + Autor1)
print("Any de llençament: " + any_de_llençament1)
print("L'estil de música: " + estil1)
print()
input("Pitja una tecla per veure els usuaris disponibles: ")
print("        ___Usuari-1___")
print("Nom i llnatges: " + nom_complet)
print("Data de neixament: " + data_de_naixement)
print("Correu electrònic: " + correu_electrònic)
print("Població on visquis: " + població)
print()
print("        ___Usuari-2___")
print("Nom i llnatges: " + nom_complet1)
print("Data de neixament: " + data_de_naixement1)
print("Correu electrònic: " + correu_electrònic1)
print("Població on visquis: " + població1)
print()
input("Pitja una tecla per sortir del programa: ")
print("Adeu, fins més tard!!")